moves = 'LRRRLLRLLRRLRLRRRLRLRRRLRRLLRRRLRRLRLLRLLRRLRLLLLRRLRRLRLLRRLRRRLLLRRLRLRRLRRRLRRRLLRLRRRLLRRLRRRLRRLRLRRLRRLLRLRLRRRLRRLRRLRRRLRRLRRLRLRRRLRRRLRRRLLLRLRRLRLRRRLRRRLRRLRRLLRLRRLLRRLLRLRRLRLRRLRRRLRLRRLRLRRRLLRRLLRLRRRLRRRLRRRLRRRLLLRLRRLRRRLRRRLRLLRRLLRRLRLRLLRRLRRLLRRRLRLRRRLRRRR'
next = {}
with open('1.2.in') as file:
    for line in file:
        cur, left, right = line[:-1].split(' ')
        next[cur] = (left, right)


n, i, tot = len(moves), 0, 0
pos = 'AAA'
while pos != 'ZZZ':
    pos = next[pos][1 if moves[i] == 'R' else 0]
    i = (i + 1) % n
    tot += 1

print(tot)
